ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "allowClientCin7Edit" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "autoCreateEnabled" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "autoCreateThreshold" DOUBLE PRECISION NOT NULL DEFAULT 0.9;
